{
 "title": "Application health",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Application Running",
   "type": "singlestat",
   "description": "This panel indicates if the Docker container is considered running",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"imagegrayscale:8080\",job=\"imagegrayscale\"}"
    }
   ]
  },
  {
   "title": "Requests per image type",
   "type": "graph",
   "description": "A count of all transformation on different image types",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(application_transformations_total) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests by transformation type",
   "type": "graph",
   "description": "This shows a stacked graph of requests per transformation type.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=~\"/api/.*[^spans]\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Successful customer requests",
   "type": "gauge",
   "description": "We have an SLO of \"one 9\" (90%) sucecss rate for customer requests. ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(http_client_requests_seconds_sum{status=~\"2.*\"}) / sum(http_client_requests_seconds_sum{})"
    }
   ]
  },
  {
   "title": "Transformation warnings logs",
   "type": "graph",
   "description": "A graph of all warning logs per transformation type",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logback_events_total{level=~\"warn\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Transformation error logs",
   "type": "graph",
   "description": "A graph of all error logs per transformation type",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logback_events_total{level=~\"error\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Images in the database",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "application_images_in_database" }
   ]
  },
  {
   "title": "Top images transformed",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "topk(5,sum(application_images_transformed_total)by(sourceId))"
    }
   ]
  },
  {
   "title": "Most viewed images",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "topk(5, sum(application_images_viewed_total)by(name))"
    }
   ]
  }
 ]
}