{
 "title": "Live of a Counter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "sum(application_transformations_total)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_transformations_total)"
    }
   ]
  },
  {
   "title": "application_transformations_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "application_transformations_total"
    }
   ]
  },
  {
   "title": "sum(application_transformations_total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(application_transformations_total)"
    }
   ]
  },
  {
   "title": "sum(application_transformations_total)by(transformation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(application_transformations_total)by(transformation)"
    }
   ]
  },
  {
   "title": "sum(increase(application_transformations_total[5m]))",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(application_transformations_total[5m]))"
    }
   ]
  },
  {
   "title": "sum(increase(application_transformations_total[5m]))by(transformation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(application_transformations_total[5m]))by(transformation)"
    }
   ]
  },
  {
   "title": "sum(application_transformations_total)by(transformation)",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(application_transformations_total)by(transformation)",
     "legendFormat": "{{transformation}}"
    }
   ]
  },
  {
   "title": "sum(application_transformations_total)by(type)",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(application_transformations_total)by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}