apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: default
spec:
  interval: 1m0s
  path: ./local/kubernetes/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: observability
    namespace: default
