apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jaeger
  namespace: istio-system
spec:
  interval: 1m0s
  path: ./local/kubernetes/tools/istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: observability
    namespace: default
