---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: default
      interval: 5m
  values:
    ingester:
      replicas: 1
    distributor:
      replicas: 1
    minio:
      enabled: false
    storage:
      trace:
        backend: local
    traces:
      zipkin:
        enabled: true
    gateway:
      enabled: true