{
 "title": "Business dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Images in database",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "application_images_in_database" }
   ]
  },
  {
   "title": "Thumbnails cached",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "application_images_thumbnails_cached"
    }
   ]
  },
  {
   "title": "Image transformations rate by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(application_transformations_total[30s]))by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Image upload rate by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(application_images_uploaded_total[30s]))by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Image deletion rate by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(application_images_deleted_total[30s]))by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Image viewed rate by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(application_images_viewed_total[30s]))by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Image thumbnails in cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_images_thumbnails_cached",
     "legendFormat": "thumbnails in cache"
    }
   ]
  }
 ]
}