{
 "title": "Services up",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 0 },
   "content": "<br/>\n<br/>\n<h1> Technical Services </h1>\n\n\n\n"
  },
  {
   "title": "elasticsearch",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"elasticsearch\"}"
    }
   ]
  },
  {
   "title": "prometheus",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "grafana",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"grafana\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "content": "<br/>\n<br/>\n<h1> Business Services </h1>\n\n\n\n"
  },
  {
   "title": "imageorchestrator",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"imageorchestrator\"}"
    }
   ]
  },
  {
   "title": "imageholder",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"imageholder\"}"
    }
   ]
  },
  {
   "title": "imagethumbnail",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"imagethumbnail\"}"
    }
   ]
  },
  {
   "title": "imageflip",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"imageflip\"}"
    }
   ]
  },
  {
   "title": "imagegrayscale",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"imagegrayscale\"}"
    }
   ]
  },
  {
   "title": "imagerotator",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"imagerotator\"}"
    }
   ]
  },
  {
   "title": "imageresize",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"imageresize\"}"
    }
   ]
  }
 ]
}