{
 "title": "Solutions",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "1) sum of all http requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(http_request_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "2) sum of http requests grouped by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(http_request_total) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3) sum of erroneous http requests by status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (http_request_total{status=~\"(4|5)\\\\d\\\\d\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "4) increase over last 2 min of images viewed by type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase (application_images_viewed_total[2m])) by (type)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "5) increase over last 5 min of images viewed and uploaded by type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase (application_images_viewed_total[5m])) by (type)",
     "legendFormat": "viewed {{type}}"
    },
    {
     "expr": "sum (increase (application_images_uploaded_total[5m])) by (type)",
     "legendFormat": "uploaded {{type}}"
    }
   ]
  },
  {
   "title": "6) Top 3 viewed images by name",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(3,sum(application_images_viewed_total) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "7) Number of images in database",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(application_images_in_database)"
    }
   ]
  }
 ]
}