dima-frontend:
  image:
    repository: local/dima-frontend
  ingress:
    enabled: false
  tracing:
    enabled: false    
dima-imageflip:
  apm:
    enabled: false
  image:
    repository: local/dima-imageflip
  ingress:
    enabled: false
  tracing:
    enabled: false   
dima-imagegrayscale:
  apm:
    enabled: false
  image:
    repository: local/dima-imagegrayscale
  ingress:
    enabled: false
  tracing:
    enabled: false   
dima-imageholder:
  apm:
    enabled: false
  image:
    repository: local/dima-imageholder
  ingress:
    enabled: false
  tracing:
    enabled: false   
dima-imageorchestrator:
  apm:
    enabled: false
  image:
    repository: local/dima-imageorchestrator
  ingress:
    enabled: false
  tracing:
    enabled: false   
dima-imageresize:
  apm:
    enabled: false
  image:
    repository: local/dima-imageresize
  ingress:
    enabled: false
  tracing:
    enabled: false   
dima-imagerotator:
  apm:
    enabled: false
  image:
    repository: local/dima-imagerotator
  ingress:
    enabled: false
  tracing:
    enabled: false   
dima-imagethumbnail:
  apm:
    enabled: false
  image:
    repository: local/dima-imagethumbnail
  ingress:
    enabled: false
  tracing:
    enabled: false   
dima-trafficgen:
  apm:
    enabled: false
  enabled: true
  image:
    repository: local/dima-trafficgen
  ingress:
    enabled: false
  tracing:
    enabled: false   