{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- if .Values.global.tls.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- end }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-service
                port:
                  number: 80
            path: /(.*)
            pathType: Prefix
  {{- if .Values.global.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: dima-tls-cert
  {{- end }}
{{- end }}