apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-cluster
  namespace: default
spec:
  interval: 1m0s
  path: ./clusters/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: observability
    namespace: default