apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-index
spec:
  ttlSecondsAfterFinished: 60
  activeDeadlineSeconds: 120
  template:
    spec:
      containers:
        - name: kibana-index
          image: local/kibana-index:latest
          imagePullPolicy: Never  # Imported via k3d image import
      restartPolicy: OnFailure
  backoffLimit: 4
