---
apiVersion: v1
kind: Service
metadata:
  labels:
    group: olly-dima
  name: {{ template "dima-imageorchestrator.service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http-8080
    port: 8080
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}