---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{  coalesce .Values.image.tag | default .Values.global.image.tag }}
        env:
        - name: MONGODB_HOST
          value: {{ template "dima-mongodb.service.name" . }}
        - name: MONGODB_PORT
          value: {{ .Values.mongodb.port | quote }}  
        - name: SPRING_PROFILES_ACTIVE
          value: "json-log"
        - name: EVENTS_ENABLED
          value: "true"
        - name: BUSINESS_METRICS_ENABLED
          value: "true"
        - name: TRACING_TAGS_ENABLED
          value: "true"
        - name: APM_ENABLED
          value: "true"
        - name: IMAGETHUMBNAIL_BASEURL
          value: {{ template "dima-imagethumbnail.baseUrl" . }}  
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "300Mi"
            cpu: "50m"
          limits:
            memory: "800Mi"
            cpu: "250m"
