---
configMaps:
  action_file_yml: |-
    ---
    actions:
      1:
        action: delete_indices
        description: >-
          Delete non system indices older than 3 days.
        options:
          ignore_empty_list: True
          timeout_override:
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: age
          source: creation_date
          direction: older
          unit: days
          unit_count: 3
        - filtertype: pattern
          kind: regex
          value: '^[^\.].*'    
  config_yml: |-
    ---
    client:
      hosts:
        - elasticsearch-master
      port: 9200
      username: elastic
      password: changeme
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      aws_key:
      aws_secret_key:
      aws_region:
      ssl_no_validate: False
      timeout: 100
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: [‘elasticsearch’]
