---
replicas: 1

esJavaOpts: "-Xms512m -Xmx512m"

resources:
  requests:
    cpu: "250m"
    memory: "1Gi"
  limits:
    cpu: "500m"
    memory: "2Gi"

secret:
  enabled: true
  password: "changeme"

clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

volumeClaimTemplate:
  resources:
    requests:
      storage: 10Gi

lifecycle:
  postStart:
    exec:
      command:
        - bash
        - -c
        - |
          #!/bin/bash
          RETENTION=2d
          echo "applying index lifecycle management with retention period of $RETENTION days to"
          ES_URL=http://localhost:9200
          while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' $ES_URL)" != "200" ]]; do sleep 1; done
          curl -XPUT "$ES_URL/_ilm/policy/logs_policy" -H 'Content-Type: application/json' -d'{"policy":{"phases":{"delete":{"min_age":"$RETENTION","actions":{"delete":{}}}}}}'