---
kibanaConfig:
  kibana.yml: |
    elasticsearch.username: elastic
    elasticsearch.password: changeme
    server.publicBaseUrl: http://localhost:8080/kibana
    server.basePath: /kibana

resources:
  requests:
    cpu: "100m"
    memory: "1Gi"
  limits:
    cpu: "250m"
    memory: "1Gi"
