{
 "title": "Application health",
 "description": "Dashboard of application health",
 "tags": [
  "dima",
  "application"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Application Running",
   "type": "stat",
   "description": "This panel indicates if the Docker container is considered running",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(sum by(app) (up{namespace=\"dima\"}))"
    }
   ]
  },
  {
   "title": "Requests by image type",
   "type": "timeseries",
   "description": "Rate of transformations on different image types",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(application_transformations_total[2m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests by transformation type",
   "type": "timeseries",
   "description": "This shows a stacked graph of the requests per second per transformation type.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/api/image/.*[^spans]\"}[2m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Successful customer requests",
   "type": "gauge",
   "description": "We have an SLO of \"one 9\" (90%) sucecss rate for customer requests. ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(http_client_requests_seconds_sum{status=~\"2.*\"}) / sum(http_client_requests_seconds_sum{})"
    }
   ]
  },
  {
   "title": "Warnings logs",
   "type": "timeseries",
   "description": "A graph of warning logs by service",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(logback_events_total{level=~\"warn\"}[2m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "timeseries",
   "description": "A graph of all error logs by service",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(logback_events_total{level=~\"error\"}[2m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Images in the database",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(application_images_in_database)"
    }
   ]
  },
  {
   "title": "Thumbnails cached",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_images_thumbnails_cached"
    }
   ]
  }
 ]
}