{
 "title": "Business dashboard",
 "description": "Dashboard for dima application",
 "tags": [
  "dima",
  "application"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Images in database",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "application_images_in_database" }
   ]
  },
  {
   "title": "Image upload rate by type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(application_images_uploaded_total[5m]))by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Image deletion rate by type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(application_images_deleted_total[5m]))by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Most viewed images",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sum(application_images_viewed_total)by(name))"
    }
   ]
  },
  {
   "title": "Image viewed rate by type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(application_images_viewed_total[5m]))by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Thumbnails cached",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_images_thumbnails_cached"
    }
   ]
  },
  {
   "title": "Image thumbnails in cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "application_images_thumbnails_cached",
     "legendFormat": "thumbnails in cache"
    }
   ]
  },
  {
   "title": "Top images transformed",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(5,sum(application_images_transformed_total)by(sourceId))"
    }
   ]
  },
  {
   "title": "Image transformations rate by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(application_transformations_total[5m]))by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}