{
 "title": "Live of a Counter",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "sum(application_transformations_total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(application_transformations_total)"
    }
   ]
  },
  {
   "title": "application_transformations_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_transformations_total"
    }
   ]
  },
  {
   "title": "sum(application_transformations_total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(application_transformations_total)"
    }
   ]
  },
  {
   "title": "sum(application_transformations_total)by(transformation)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(application_transformations_total)by(transformation)"
    }
   ]
  },
  {
   "title": "sum(increase(application_transformations_total[5m]))",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(application_transformations_total[5m]))"
    }
   ]
  },
  {
   "title": "sum(increase(application_transformations_total[5m]))by(transformation)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(application_transformations_total[5m]))by(transformation)",
     "legendFormat": "{{transformation}}"
    }
   ]
  },
  {
   "title": "sum(application_transformations_total)by(transformation)",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(application_transformations_total)by(transformation)",
     "legendFormat": "{{transformation}}"
    }
   ]
  },
  {
   "title": "sum(application_transformations_total)by(type)",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum(application_transformations_total)by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}