---
replicas: 1
resources:
  requests:
    cpu: "250m"
    memory: "1500Mi"
  limits:
    cpu: "500m"
    memory: "1500Mi"
secret:
  enabled: true
  password: "changeme"
replicas: 1
clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
volumeClaimTemplate:
  resources:
    requests:
      storage: 10Gi