config:
  clients:
    - url: http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push

  snippets:
    pipelineStages:
      - cri: {}
      - json:
          expressions:
            time: '"@timestamp"'
            message: message
            level: level
            trace_id: traceId
            span_id: spanId
      - labels:
          level: level
          trace_id: trace_id
      - timestamp:
          format: RFC3339
          source: "time"
      - output:
          source: message